import Foundation
import Testing

@testable import SpindleCore

@Suite
struct CaptureFilterTests {
    private func copy(from app: String?, declaring types: [PasteboardFlavor] = [.plainText]) -> CapturedCopy {
        CapturedCopy(
            items: [CapturedItem(representations: [Representation(flavor: .plainText, data: Data("x".utf8))])],
            declaredTypes: types,
            sourceBundleID: app,
            changeCount: 1,
            capturedAt: .now)
    }

    @Test
    func keepsOrdinaryCopies() {
        #expect(CaptureFilter().skipReason(for: copy(from: "com.apple.Safari")) == nil)
    }

    @Test(arguments: [PasteboardFlavor.concealed, .transient, .autoGenerated, PasteboardFlavor("net.antelle.keeweb")])
    func skipsMarkedCopies(_ marker: PasteboardFlavor) {
        let marked = copy(from: "com.apple.Safari", declaring: [.plainText, marker])
        #expect(CaptureFilter().skipReason(for: marked) == .privacyMarker)
    }

    @Test
    func skipsIgnoredApps() {
        #expect(
            CaptureFilter().skipReason(for: copy(from: "com.1password.1password"))
                == .ignoredApp("com.1password.1password"))
    }

    @Test
    func recognizesMenuBarExtrasByTheirPasteboardTypes() {
        // Attributed to Safari because it was frontmost, but the types give the real source away.
        let fromExtra = copy(
            from: "com.apple.Safari", declaring: [.plainText, PasteboardFlavor("com.bitwarden.desktop.item")])
        #expect(CaptureFilter().skipReason(for: fromExtra) == .ignoredApp("com.bitwarden.desktop"))
    }

    @Test
    func theIgnoreListIsEditable() {
        var filter = CaptureFilter()
        filter.ignoredApps.remove("com.apple.keychainaccess")
        filter.ignoredApps.insert("com.tinyspeck.slackmacgap")
        #expect(filter.skipReason(for: copy(from: "com.apple.keychainaccess")) == nil)
        #expect(filter.skipReason(for: copy(from: "com.tinyspeck.slackmacgap")) != nil)
    }

    @Test
    func universalClipboardCopiesCanBeTurnedOff() {
        let remote = copy(from: "com.apple.Safari", declaring: [.plainText, .remoteClipboard])
        #expect(CaptureFilter().skipReason(for: remote) == nil)
        #expect(CaptureFilter(keepsRemoteCopies: false).skipReason(for: remote) == .remoteCopy)
    }
}

@Suite
struct CapturePauseTests {
    private let now = Date(timeIntervalSince1970: 1_790_000_000)

    @Test
    func admitsCopiesByDefault() {
        var pause = CapturePause()
        #expect(pause.admit(at: now) == nil)
    }

    @Test
    func aTimedPauseEndsOnItsOwn() {
        var pause = CapturePause()
        pause.pause(until: now.addingTimeInterval(300))
        #expect(pause.admit(at: now.addingTimeInterval(299)) == .paused)
        #expect(pause.admit(at: now.addingTimeInterval(300)) == nil)
        #expect(pause.pausedUntil == nil)
    }

    @Test
    func anOpenEndedPauseLastsUntilResumed() {
        var pause = CapturePause()
        pause.pause(until: nil)
        #expect(pause.admit(at: now.addingTimeInterval(86_400 * 365)) == .paused)
        pause.resume()
        #expect(pause.admit(at: now) == nil)
    }

    @Test
    func ignoreNextCopySkipsExactlyOne() {
        var pause = CapturePause()
        pause.skipNextCopy()
        #expect(pause.admit(at: now) == .skippedOnce)
        #expect(pause.admit(at: now) == nil)
    }

    @Test
    func aPauseDoesNotUseUpIgnoreNextCopy() {
        var pause = CapturePause()
        pause.pause(until: now.addingTimeInterval(60))
        pause.skipNextCopy()
        #expect(pause.admit(at: now) == .paused)
        #expect(pause.admit(at: now.addingTimeInterval(61)) == .skippedOnce)
    }
}
