/// A pasteboard type identifier, such as `public.utf8-plain-text`.
///
/// SpindleCore doesn't import AppKit, so flavors are plain uniform type identifier strings. The
/// system layer converts them to and from `NSPasteboard.PasteboardType`.
public struct PasteboardFlavor: RawRepresentable, Hashable, Sendable, CustomStringConvertible {
    public let rawValue: String

    public init(rawValue: String) {
        self.rawValue = rawValue
    }

    public init(_ rawValue: String) {
        self.rawValue = rawValue
    }

    public var description: String { rawValue }
}

// MARK: - Content flavors

extension PasteboardFlavor {
    public static let plainText = PasteboardFlavor("public.utf8-plain-text")
    public static let rtf = PasteboardFlavor("public.rtf")
    public static let rtfd = PasteboardFlavor("com.apple.flat-rtfd")
    public static let html = PasteboardFlavor("public.html")
    public static let fileURL = PasteboardFlavor("public.file-url")
    public static let url = PasteboardFlavor("public.url")
    public static let png = PasteboardFlavor("public.png")
    public static let tiff = PasteboardFlavor("public.tiff")
    public static let jpeg = PasteboardFlavor("public.jpeg")
    public static let heic = PasteboardFlavor("public.heic")
    public static let pdf = PasteboardFlavor("com.adobe.pdf")
    public static let color = PasteboardFlavor("com.apple.cocoa.pasteboard.color")

    /// The flavors Spindle reads, in the order it prefers them. Anything else on the pasteboard is
    /// ignored: reading a type can make the source app produce expensive data on demand.
    public static let captured: [PasteboardFlavor] = [
        .plainText, .rtf, .rtfd, .html, .fileURL, .url, .png, .heic, .jpeg, .tiff, .pdf, .color,
    ]

    public var isCaptured: Bool { Self.captured.contains(self) }

    public var isImage: Bool { self == .png || self == .tiff || self == .jpeg || self == .heic }

    /// The largest payload Spindle reads for this flavor. Bigger payloads are skipped, not truncated.
    ///
    /// Reads happen on the main thread, and a 20 MB read takes about 5 ms on an M4, so the caps keep
    /// a single copy from stalling the app.
    public var captureLimit: Int {
        switch self {
        case .png, .tiff, .jpeg, .heic, .pdf: 50 << 20
        case .fileURL, .url, .color: 64 << 10
        default: 16 << 20
        }
    }
}

// MARK: - Metadata and privacy markers

extension PasteboardFlavor {
    /// The bundle identifier of the app that wrote the pasteboard, when that app declares it.
    public static let source = PasteboardFlavor("org.nspasteboard.source")

    /// Present on items that arrived through Universal Clipboard from another device.
    public static let remoteClipboard = PasteboardFlavor("com.apple.is-remote-clipboard")

    public static let concealed = PasteboardFlavor("org.nspasteboard.ConcealedType")
    public static let transient = PasteboardFlavor("org.nspasteboard.TransientType")
    public static let autoGenerated = PasteboardFlavor("org.nspasteboard.AutoGeneratedType")

    /// Types that mean "don't record this copy": the nspasteboard.org markers, plus older markers
    /// that some password managers and utilities still write instead.
    public static let privacyMarkers: Set<PasteboardFlavor> = [
        .concealed, .transient, .autoGenerated,
        PasteboardFlavor("com.agilebits.onepassword"),
        PasteboardFlavor("com.typeit4me.clipping"),
        PasteboardFlavor("de.petermaurer.TransientPasteboardType"),
        PasteboardFlavor("Pasteboard generator type"),
        PasteboardFlavor("net.antelle.keeweb"),
    ]
}
